# Generated by Django 2.2.6 on 2022-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_uploadmnist_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmnist',
            name='mnistfile',
            field=models.FileField(upload_to='mnist'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='modelfile',
            field=models.FileField(upload_to='models'),
        ),
    ]
