# Generated by Django 2.2.6 on 2022-07-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uploadmnist1_uploadmodel1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadmnist1',
            new_name='uploadmnist2',
        ),
        migrations.RenameModel(
            old_name='Uploadmodel1',
            new_name='Uploadmodel2',
        ),
    ]
