# Generated by Django 2.2.6 on 2022-07-04 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220704_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='mnist2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mnistfile', models.FileField(upload_to='mnist')),
                ('created_time', models.CharField(default=django.utils.timezone.now, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('modelfile', models.FileField(upload_to='models')),
                ('created_time', models.CharField(default=django.utils.timezone.now, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='uploadmnist2',
        ),
        migrations.DeleteModel(
            name='Uploadmodel2',
        ),
    ]
